package fm.lossless.auth.exception;

public enum AuthErrorCode {
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    VALIDATION_FAILED,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_IN_USE,
    INVALID_REFRESH_TOKEN,
    DEFAULT_ROLE_NOT_CONFIGURED,
    AUTH_FEATURE_NOT_IMPLEMENTED,
    PASSWORD_LOGIN_NOT_AVAILABLE,
    UNSUPPORTED_SOCIAL_PROVIDER,
    INVALID_SOCIAL_TOKEN,
    SOCIAL_EMAIL_REQUIRED,
    SOCIAL_EMAIL_NOT_VERIFIED,
    SOCIAL_AUTH_MISCONFIGURED,
    REQUEST_INVALID,
    INTERNAL_ERROR
}
