spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/appdb?options=-c%20TimeZone=UTC
    username: app
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_versioned_data: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  jackson:
    time-zone: UTC

server:
  port: 8080
