package fm.lossless.tracks.exception;

public enum TrackErrorCode {
    TRACK_FILE_REQUIRED,
    TRACK_FILE_EMPTY,
    TRACK_FILE_TOO_LARGE,
    TRACK_FILE_EXTENSION_NOT_ALLOWED,
    TRACK_FILE_CONTENT_TYPE_NOT_ALLOWED,
    TRACK_FILE_FORMAT_NOT_ALLOWED,
    TRACK_GENRE_REQUIRED,
    TRACK_GENRE_NOT_FOUND,
    TRACK_PURCHASE_LINK_INVALID,
    TRACK_PURCHASE_LINK_LIMIT_EXCEEDED,
    TRACK_STORAGE_FAILED,
    TRACK_NOT_FOUND,
    TRACK_AUDIO_NOT_FOUND,
    TRACK_AUDIO_RANGE_INVALID,
    TRACK_FEED_LIMIT_INVALID,
    TRACK_FEED_CURSOR_INVALID,
    TRACK_UPLOAD_FAILED
}
